### ISSUE TITLE
Internet Problems on Mac OS X

### ISSUE THREAD

**Issue by eawo2k4** [sebastianbiallas/pearpc#17]
Hi,I do not know how to Get the Internet Working On Mac Cuse i look at the Guide and Look it up to It Does not make Sense to me, Let me Know Thanks

**Comment by puellanivis** [comment]
The networking in PearPC was never particularly well developed, due to every Operating System providing quite complicated and incompatible methods of providing an emulated network device.

Since the most productive development of PearPC came to a close after OS X was released for x86 architectures (which was likely 99% of why PearPC was popular in the first place.) there was extremely little actual work provided by us the developers and the community at large for running PearPC on an Intel Mac.

At the time, MacOnLinux was available, and had much better compatibility and performance than PearPC, which did not even have JITC support available for PowerPC machines…

**Comment by eawo2k4** [comment]
So you're Saying is that I cannot Run Internet on it But How can i add Files more applications to it like Games and stuff?

**Comment by puellanivis** [comment]
Summary: I’m sorry, but I don’t believe anyone has done this before, and thus it is currently unknown how to do any of this. You would unfortunately have to pioneer getting this accomplished.

I understand your frustration, and I sympathize. It is clearly difficult to get files onto a PearPC emulation without an internet connection. But PearPC predates Intel Mac OS X by at least a year. We maintainers and the community as a whole simply had no way to address providing PearPC internet access on Mac OS X as it was not a possibility during the time of highest development.

If you have any luck providing PearPC with internet while on Mac OS X, that would be great news, and the community (as small as it has become) would likely appreciate it nonetheless. But I am unaware of anyone having spent the time to get this working.

I’m sorry.
