### ISSUE TITLE
How do I install this if I want it for normal use?

### ISSUE THREAD

**Issue by andy0dvlpr** [sebastianbiallas/pearpc#20]
How am I meant to install this? I have downloaded it but I can't find an exe or any sort of help.

**Comment by puellanivis** [comment]
Sorry for the extremely late response.

This package dates back well over 10 years. As such, the standard install instructions at the time were:
```
$ ./configure
$ make
$ make install
```

Unfortunately, no one has had time or want of effort to compile binaries like was done when this project was big. It is an extremely nitch interest, and as a result still requires the old “compile it yourself” process to install.

Although, you may be able to find some copies of the binary from people who used to compile it, but as mentioned, since this is now over 10 years old since its big days… this is probably unlikely.

**Comment by aryan-sudo** [comment]
What OS are you running?

**Comment by andy0dvlpr** [comment]
> What OS are you running?

Hello! Sorry for the late response. I prefer using Windows, but if the only option available is what @puellanivis suggested, then I don't mind making a Linux VM and using that.

**Comment by aryan-sudo** [comment]
For windows if you want to install this version, then you should have a gcc compiler installed. If you want to install an older version, then download a win32-Jitc release from [here](http://pearpc.sourceforge.net/downloads.html) you want a easier installation, then run a Linux VM. Then download a zip file of this version or a source archive of your version from the website I mentioned. After that go to the [Compiling Wiki](https://github.com/sebastianbiallas/pearpc/wiki/Compiling) and follow the instructions for Linux.

**Comment by andy0dvlpr** [comment]
> For windows if you want to install this version, then you should have a gcc compiler installed. If you want to install an older version, then download a win32-Jitc release from [here](http://pearpc.sourceforge.net/downloads.html) you want a easier installation, then run a Linux VM. Then download a zip file of this version or a source archive of your version from the website I mentioned. After that go to the [Compiling Wiki](https://github.com/sebastianbiallas/pearpc/wiki/Compiling) and follow the instructions for Linux. Then continue with the [Wiki](https://github.com/sebastianbiallas/pearpc/wiki). Please note that I never compiled PearPC on windows before so you can’t get help from me.

Thank you. This worked. I will now close the issue.
